### ISSUE TITLE
ffmpeg not found

### ISSUE THREAD

**Issue by elpredatoro** [Jeeaaasus/youtube-dl#101]
`ERROR: Postprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location`

`WARNING: You have requested merging of multiple formats but ffmpeg is not installed. The formats won't be merged`

the files are downloaded but not properly merged, so they are not added to archive.txt, and next time it tries to download them again with the same result.

**Comment by Jeeaaasus** [comment]
Please update to latest image version, add environment `youtubedl_debug=true` and post logs of a failed run.

**Comment by elpredatoro** [comment]
I've downloaded the latest version, and everything works fine now.
