### ISSUE TITLE
youtubedl_interval is set to 'false' but not exiting

### ISSUE THREAD

**Issue by dnick5000** [Jeeaaasus/youtube-dl#108]
Hi, I'm getting an error with the latest version. I have youtubedl_interval set to false, but the log says it's not permitted when trying to kill the program. Instead it just starts running all over again. Here is the snippet from my log:

> 2024-12-25 08:56:18 - execution took 6 minutes
> yt-dlp version: 2024.12.23
> youtubedl_interval is set to 'false', container will now exit.
> /app/youtube-dl/youtube-dl.sh: line 75: kill: (70) - Operation not permitted
> 2024-12-25 08:56:18,166 INFO exited: youtube-dl (exit status 0; expected)
> 2024-12-25 08:56:19,169 INFO spawned: 'youtube-dl' with pid 259

**Comment by Jeeaaasus** [comment]
My bad. I must have just put a placeholder for that feature and forgotten to validate it what so ever.

Should be fixed now. I have also triggered a new latest image to be built. Let me know if it still doesn't work as expected!

**Comment by dnick5000** [comment]
Thank you so much! It's working perfectly now!
