### ISSUE TITLE
Apply PUID:PGID to files at time of download completion.

### ISSUE THREAD

**Issue by robdaly** [Jeeaaasus/youtube-dl#13]
All files that are downloaded using the Docker image don't conform to the PUID:PGID supplied to the container, and still map to root:root. 

Docker run example:
```
docker run -d  -e PGID=1000 -e PUID=1000 -v ~/Docker/youtube-dl/downloads:/downloads -v ~/Docker/youtube-dl/config:/config jeeaaasustest/youtube-dl
```
Example config/channels.txt:

```
# one per line
https://www.youtube.com/playlist?list=PLsooighzcilZG4DjnuoE7Mor0hkbKWEma
```

Example output: 
```
-rw-r--r-- 1 root root 3055342 Apr 29 10:17 'Michael Jordan THE SHOT on Ehlo.mp4'
```

**Comment by Jeeaaasus** [comment]
Hey @robdaly! I appreciate the bug report!
Would you mind testing the beta image for me?

continuing on your example run:
```
docker run -d  -e PGID=1000 -e PUID=1000 -v ~/Docker/youtube-dl/downloads:/downloads -v ~/Docker/youtube-dl/config:/config jeeaaasustest/youtube-dl:beta
```

**Comment by robdaly** [comment]
Thanks, @Jeeaaasus! Sorry I missed the notification on this, or I would have responded sooner. Works perfectly! Thanks for the quick response.

**Comment by Jeeaaasus** [comment]
No worries! Great, it's been merged to latest.
Make sure you don't continue using the beta tag, I only use it for testing sometimes.
