### ISSUE TITLE
playlist-end default

### ISSUE THREAD

**Issue by publicvirtualvoid** [Jeeaaasus/youtube-dl#17]
First of all, great package! Thanks very much.
One suggestion: `playlist-end` is set to 4 by default in the args file, this tripped me up for a while.

**Comment by Jeeaaasus** [comment]
Thanks, great to hear that it is useful!
I can't recall anymore, why that is the case, might have been an issue with making too many requests to youtube. 
I'll look into changing the default.
Thank you very much for the taking time and letting me know!
