### ISSUE TITLE
help not found videos

### ISSUE THREAD

**Issue by cruix89** [Jeeaaasus/youtube-dl#18]
hello master, this script is amazing

my container is returning 0 videos for downloader, could you help me if i did something wrong?

[cont-init.d] 99-init.d-finish: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[youtube:channel] ___channel hidden___: Downloading channel page
[youtube:playlist] ___channel hidden___: Downloading webpage
[download] Downloading playlist: ___channel hidden___
[youtube:playlist] playlist ___channel hidden___: Downloading 0 videos
[download] Finished downloading playlist: ___channel hidden___
[youtube:channel] ___channel hidden___: Downloading channel page
[youtube:playlist] ___channel hidden___: Downloading webpage
[download] Downloading playlist: ___channel hidden___
[youtube:playlist] playlist ___channel hidden___: Downloading 0 videos
[download] Finished downloading playlist: ___channel hidden___
2020-11-10 19:16:36 - execution took 21 seconds
youtube-dl version: 2020.11.01.1

**Comment by Jeeaaasus** [comment]
Welcome @cruix89!
No you probably didn't do anything wrong!
This is a very recent known issue but it looks to be getting fixed soon-ish.
My image will be updated once it's fixed, make sure to update your container in the near future.

I'll leave this issue open, for others to see, until it is fixed and my image gets updated! 😊

**Comment by cruix89** [comment]
thanks for the quick return, let's wait, great job!

**Comment by wjbridge** [comment]
I am happy you kept this open :). I am having the same problem. You indicated that this is a very recent issue? Do you have the location of the issue list for youtubedl? Since they took the repo down, trying to find the replacement location so I can track the issue list.

**Comment by Jeeaaasus** [comment]
@wjbridge I figured someone else was also going to notice this. 😊
yeah it's a bit tricky because of that.. seems like the original project is dead right now, I'm changing over the image to [yt-dlc](https://github.com/blackjack4494/yt-dlc). At least for now. That is where I was looking at the current issue and I believe [this](https://github.com/blackjack4494/yt-dlc/commit/00c38ef28dad5abc8c32b7084f215f1aacc61292) commit fixes it.

**Comment by Jeeaaasus** [comment]
It's done, time to update your image!

**Comment by wjbridge** [comment]
Thanks for the hard work!
