### ISSUE TITLE
Switching back to youtube-dl

### ISSUE THREAD

**Issue by shockey** [Jeeaaasus/youtube-dl#21]
Any thoughts on switching back to `youtube-dl` from `yt-dlc`, since [it's back to normal now](https://github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/)?

For my part: since the youtube-dl debacle started, I've been having issues with the "download-all-playlists-for-user" functionality I rely on. It looks like current `youtube-dl` has this fixed, while `yt-dlc` does not.

Happy to help PR this if there's interest.

**Comment by Jeeaaasus** [comment]
Hello @shockey! Thank you for opening an issue 😊
I absolutely want to switch back. I was waiting to see that development actually goes back to normal and no other issues arose and now that yt-dlc seems to no longer be at feature parity, I'm happy to switch back.

I have pushed a new image with the beta tag `jeeaaasustest/youtube-dl:beta`
Would you mind giving that image a try and confirming this issue you have, is indeed fixed?
