### ISSUE TITLE
Add a graphical interface

### ISSUE THREAD

**Issue by PDSCi996** [Jeeaaasus/youtube-dl#26]
Thank you very much for your hard work. Your container is the most convenient I have seen to monitor YouTube updates, and it solves my big problem.
However, I am very interested in some YouTube videos, and I want to download the whole video, but I use docker in the Synology system. There is no graphical interface. It is very troublesome to check the container status or do other things. Whether it is more perfect to add a graphical interface in future versions, like "https://github.com/nbr23/youtube-dl-server".
And YouTube-dl supports hundreds of video sites. I tried to fill in the addresses of some of the video sites I often watch into the "channels.txt" file, such as "https://space.bilibili.com/157761/video", although it is also It ends with a video, but it cannot be monitored. I don't know why. Can the container only monitor one YouTube website?

**Comment by Jeeaaasus** [comment]
Hey @PDSCi996 thank you for the kind words! 😊

No it's not restricted to YouTube only.
The 'channels.txt' file is simply given to youtube-dl with the `--batch-file` argument which means you can enter whichever URLs youtube-dl can handle, be that channels, playlists or videos.

But it seems youtube-dl poorly supports bilibili and cannot download channels or playlist from bilibili.
According to: https://stackoverflow.com/a/60550389
```
bilibili.com has some Javascript involved to setup the video player and fetch the video files.
There is no way so you can extract the whole playlist using youtube-dl.
```
also in that post they talk about another program that you may want to check out, [annie](https://github.com/iawia002/annie)


Regarding a GUI, it's not something I will be adding anytime soon but possibly in the future, if there is enough interest.

**Comment by PDSCi996** [comment]
> Hey @PDSCi996 thank you for the kind words! 
> 
> No it's not restricted to YouTube only.
> The 'channels.txt' file is simply given to youtube-dl with the `--batch-file` argument which means you can enter whichever URLs youtube-dl can handle, be that channels, playlists or videos.
> 
> But it seems youtube-dl poorly supports bilibili and cannot download channels or playlist from bilibili.
> According to: https://stackoverflow.com/a/60550389
> 
> ```
> bilibili.com has some Javascript involved to setup the video player and fetch the video files.
> There is no way so you can extract the whole playlist using youtube-dl.
> ```
> 
> also in that post they talk about another program that you may want to check out, [annie](https://github.com/iawia002/annie)
> 
> Regarding a GUI, it's not something I will be adding anytime soon but possibly in the future, if there is enough interest.

Thank you very much for your reply, because my computer level is relatively poor, it is really difficult for me to deploy annie.
But I found another solution to deploy RSSHuB "https://github.com/DIYgod/RSSHub". After deploying rsshub on my Synology, I can read the page information of bilibili in rss format, and then Fill in the rss address into the "channels.txt" file, and then you can download the video like monitoring youtube, although it is not perfect.
I also want to ask a technical question. If I have downloaded certain videos on YouTube, but I am not satisfied with these videos or accidentally deleted them, and need to download them again, I must delete the corresponding ones from the "archive.txt" file Video ID, otherwise it won’t be downloaded, but what should I do when I don’t know the ID of these videos? Is it necessary to delete all the contents in the "archive.txt" file? What happens if you delete everything?

**Comment by PDSCi996** [comment]
> > Hey @PDSCi996 thank you for the kind words!
> > No it's not restricted to YouTube only.
> > The 'channels.txt' file is simply given to youtube-dl with the `--batch-file` argument which means you can enter whichever URLs youtube-dl can handle, be that channels, playlists or videos.
> > But it seems youtube-dl poorly supports bilibili and cannot download channels or playlist from bilibili.
> > According to: https://stackoverflow.com/a/60550389
> > ```
> > bilibili.com has some Javascript involved to setup the video player and fetch the video files.
> > There is no way so you can extract the whole playlist using youtube-dl.
> > ```
> > 
> > 
> > also in that post they talk about another program that you may want to check out, [annie](https://github.com/iawia002/annie)
> > Regarding a GUI, it's not something I will be adding anytime soon but possibly in the future, if there is enough interest.
> 
> Thank you very much for your reply, because my computer level is relatively poor, it is really difficult for me to deploy annie.
> But I found another solution to deploy RSSHuB "https://github.com/DIYgod/RSSHub". After deploying rsshub on my Synology, I can read the page information of bilibili in rss format, and then Fill in the rss address into the "channels.txt" file, and then you can download the video like monitoring youtube, although it is not perfect.
> I also want to ask a technical question. If I have downloaded certain videos on YouTube, but I am not satisfied with these videos or accidentally deleted them, and need to download them again, I must delete the corresponding ones from the "archive.txt" file Video ID, otherwise it won’t be downloaded, but what should I do when I don’t know the ID of these videos? Is it necessary to delete all the contents in the "archive.txt" file? What happens if you delete everything?

I downloaded the video today and found a new problem, the log shows
"Error: AtomicParsley could not be found. Please install.
Retrospective (last call):
    In post_process, the file "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2102
      files_to_delete, info = pp.run(info)
    Running file "/usr/lib/python3.8/site-packages/youtube_dl/postprocessor/embedthumbnail.py", line 93
      Raise EmbedThumbnailPPError('AtomicParsley not found. Please install.')
youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError: AtomicParsley was not found. Please install. "
I saw that the pictures of the video can’t be encapsulated into the video. I don’t know why. I remember that the container was only available when it was deployed. I don’t know why it suddenly happened.
