### ISSUE TITLE
Questions about webui mode

### ISSUE THREAD

**Issue by PDSCi996** [Jeeaaasus/youtube-dl#31]
Thank you very much for your hard work.
I see that there is already a webui container on dockerhub. I downloaded and started it, but there is no setting in the port setting. I don’t know how to start the graphical interface of this container. I hope there are specific instructions. Thanks a lot.

**Comment by Jeeaaasus** [comment]
Yeah you could try it out, it's not finished, not stable, not documented, might not work and definitely not beautiful.
You need to expose port 80 from the container to access the webpage.

You do this by adding `-p <PORT>:80` to your docker run command. with `<PORT>` being the port you want to access it on, this port cannot be used by another service.

Example:
```
docker run -d \
    --name youtube-dl-beta \
    -v youtube-dl-beta_data:/config \
    -v <PATH>:/downloads \
    -p 80:80 \
    jeeaaasustest/youtube-dl:webui-beta
```
And you would access it on http://`<IP>`:80. If the container is running on your local machine that would be http://localhost:80.

**Comment by PDSCi996** [comment]
Thank you for your prompt reply. The container does have bugs, and errors continue to appear. The error code is as follows.
![bug](https://user-images.githubusercontent.com/50539888/110209942-36093a00-7eca-11eb-96e1-16da238b31b8.jpg)

**Comment by Jeeaaasus** [comment]
Did you try another port?

**Comment by Jeeaaasus** [comment]
I'm changing the inside port to 8080.
`-p <PORT>:8080`
Adjust your run command and try again with the updated image.

**Comment by PDSCi996** [comment]
Thank you very much for your effort. The container has been successfully started, and it can also operate as if there is no graphical interface, but after I fill in a certain YouTube address in the address bar and click the downlaod button, an error appears. The code is as follows. I tried more than one. The video addresses all have the same error.
![错误代码](https://user-images.githubusercontent.com/50539888/110240493-1c79f800-7f87-11eb-8e27-ed75a7f93962.jpg)

**Comment by changyou68** [comment]
After yesterday's update, Merging function of [ffmpeg] seems not working:

```
today at 13:08  [download] Download completed
today at 13:08  [ffmpeg] Merging formats into "/downloads/test_video.mp4"
today at 13:08  ERROR: Error relocating /usr/bin/ffmpeg: av_opt_child_class_iterate: symbol not found
```

Thanks for the great work!

**Comment by PDSCi996** [comment]
Hello, today I updated weiui's latest container, but found that it can’t be used anymore. All of the “Args”, “Archile” and “Channels” in the “EDIT” option can’t be opened, and it prompts “Internal Server Error”. Fill in the YouTube connection in the address bar Clicking "Download" also prompts the same error.
I checked the logs again and took screenshots of a few logs indicating errors for reference.
There is also a small suggestion, whether it is possible to temporarily keep the previous version for a period of time when updating the container to prevent the embarrassing situation that the new container cannot be used with new defects.
Thank you again for your hard work.
![错误1](https://user-images.githubusercontent.com/50539888/114291311-faf5ba00-9ab8-11eb-83e6-dac7c0938f07.png)
![错误2](https://user-images.githubusercontent.com/50539888/114291344-35f7ed80-9ab9-11eb-8c66-0ebd042f99ba.png)
![错误3](https://user-images.githubusercontent.com/50539888/114291349-3abca180-9ab9-11eb-8bd9-6f2ee68aa999.png)
![错误4](https://user-images.githubusercontent.com/50539888/114291351-3e502880-9ab9-11eb-9844-fc16f5f6e73c.png)

**Comment by Jeeaaasus** [comment]
I don't know why you would be having file permission issues, the change was not anything remotely related to that.
All permissions should be fixed on startup.

You don't have to delete the old image. You could save the old image when you update and then later go back.
