### ISSUE TITLE
[Errno 111] Connection refused

### ISSUE THREAD

**Issue by theskyisthelimit** [Jeeaaasus/youtube-dl#34]
Hello,

The youtube-dl container somehow stopped working yesterday. I'm getting the following error:
`
Vox: Downloading webpage
today at 08:59  ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused')))
`
I recreated the docker container and deployed it again, but it didn't help. I'm also using youtube-dl-server which still works, so I don't think it's the internet connection or anything like  that.

Any ideas?

**Comment by Jeeaaasus** [comment]
Hi @theskyisthelimit!

Are you running `:latest` and is the image up to date?

That's a very generic sounding error, You could try youtube-dl in verbose mode to see if you get a better clue.
Add `-e youtubedl_debug=true`.

Have you tried going back one version? 2021.03.14 as released yesterday, maybe something broke then.
The previous version was `2021.03.03`, image: `jeeaaasustest/youtube-dl:v2021.03.03`.
Preferably try this with a new container.

**Comment by theskyisthelimit** [comment]
Hey @Jeeaaasus 

Thanks for the quick reply & advice with the debug mode. I was able to locate the problem. Just some hours, after you've released a newer version my proxy crashed and I din't notice. I totally forgot I was using it and of course that blocking the requests and that was the reason why I could ping youtube from within the docker image. Im supper happy it's working again!

Thanks again for your time and keep up the good work!

**Comment by Jeeaaasus** [comment]
No problem 👍
Thanks :)
