### ISSUE TITLE
Merging function of [ffmpeg] seems not working now

### ISSUE THREAD

**Issue by changyou68** [Jeeaaasus/youtube-dl#36]
After yesterday's update, Merging function of [ffmpeg] seems not working:

```
today at 13:08  [download] Download completed
today at 13:08  [ffmpeg] Merging formats into "/downloads/test_video.mp4"
today at 13:08  ERROR: Error relocating /usr/bin/ffmpeg: av_opt_child_class_iterate: symbol not found
```

Thanks for the great work!

**Comment by Jeeaaasus** [comment]
Hi @changyou68
Thank you for reporting an issue! :)

Yes I see something is messed up with ffmpeg.
While I investigate the issue, you can use any of the static images, these should work fine. (newest: `v2021.04.07`)

**Comment by Jeeaaasus** [comment]
The image `latest` should be working now!
Thanks again @changyou68! :)

**Comment by changyou68** [comment]
The lastest image has been tested working now. 

Thank you so much for quick fixing! :)
