### ISSUE TITLE
Probably phantom.js missing

### ISSUE THREAD

**Issue by O491dogan** [Jeeaaasus/youtube-dl#38]
Hi! I really want to thank you for providing youtube-dl in this awesome self updating docker!

I updated the docker to your newest version and I'm getting an Error like this:
`ERROR: PhantomJS executable not found in PATH, download it from http://phantomjs.org`

I tried to download the video with youtube-dl outside of docker with the most recent version and it was working fine.
May it be possible, that something (PhantomJS) is missing or not in the right place inside the container?

Thanks for checking!

Regards, O491

**Comment by Jeeaaasus** [comment]
Welcome O491 and thank you for taking the time and opening an issue!

That is an error I've never seen, is it consistently coming up every time a specific video is being downloaded?
Yes it sounds like a dependency I've not included in the image, however PhantomJS is basically not mentioned on the youtube-dl github anywhere and it's not tagged as a dependency in pip, but it indeed does sound like a dependency.

I would like one of two things from you, if you don't mind.
1. If you are able to and would like to help trouble shoot.
Install PhantomJS inside your running container by doing `python3 -m pip install PhantomJS` or alternatively from your docker host, assuming your container is named `youtube-dl`, doing `docker exec youtube-dl bash -c 'python3 -m pip install PhantomJS'`.
Then restarting it or whatever to check if the error persists.
2. If I would trouble shoot.
I need a URL that consistently errors to be able to trouble shoot myself.
The contents of your `args.conf` file.

Thanks again for helping!

**Comment by O491dogan** [comment]
Hi again, 

well - don't thank me :-D. We all benefit from your work!

Okay, back to topic:
I went for route number 1 to help you trouble shooting.

Problem 1: It's not always the same video when this error occurs (these are the errors I hate the most, if it's not easily reproducable)

Problem 2: After successfully installing PhantomJS with your prepared command
`root@NAS:~# docker exec youtube-dl_yt-dl-ph-user_1 bash -c 'python3 -m pip install PhantomJS'

Collecting PhantomJS
  Downloading phantomjs-1.4.1-py3-none-any.whl (9.8 kB)
Installing collected packages: PhantomJS
Successfully installed PhantomJS-1.4.1
root@NAS:~# `

The problem still occurs. 

I'm going to do another test wit the non-dockered version, because yesterday I only downloaded the video with the non-dockered version which brought up an error inside the container. 
As we know now, the problem might not be only related to some kind of "special" videos.

I'm going to load my whole playlist in the non-dockered version and see, if the errors raise there too.

If so, the extractor might be broken right now.

I'm going to update this issue as soon as I have tested it!

Thanks!

**Comment by Jeeaaasus** [comment]
yeah these situations are annoying, be sure to use verbose mode to get extended logs for when you manage to catch the error!
it would be very helpful with a verbose log.
calling youtube-dl with param `--verbose` or adding the same to the `args.conf` file.

Also be aware the installation inside the container is not permanent, it will get uninstalled if you update the image or recreate the container. It will survive stop & start or restarts.

**Comment by O491dogan** [comment]
Hi again!

Unfortunately, there's not much to let you know so far. I'm trying to dig a bit deeper. Maybe tomorrow trying a few things.

So far I have noticed that the playlist on my desktop system is running fine. But I also noticed, that it runs Python 3.6. The docker uses 3.8 - don't know if this makes any difference. 
If I had to make a guess, I'd say no.

**Comment by O491dogan** [comment]
Hi again, sorry for not updating so long!

Well I have good and bad news :-)
If you prefer to eat your dessert at first: It seems like your image is fine! Sorry for causing confusion!!

The bad news: I don't know what really happened. I tried it again within the docker and it's not giving me these errors anymore. Instead some titles cannot be extracted which is totally fine. I checked the links when the errors rise and they link to another site which is not the intended extractor site. So everything seems fine now.

I have to check if there were changes in the extractor with the newest release.

Thank you for your support during this issue. Do you want to close it or shall I?
And please keep up your work - it's great because the OS of my NAS stays untouched :-)

**Comment by Jeeaaasus** [comment]
No worries O491! I'm really glad my project is useful to you.
Feel free to open another issue in the future regarding this, or other improvements :)
