### ISSUE TITLE
Container youtube-dlp does not have yt-dlp's SponSkrub integration?

### ISSUE THREAD

**Issue by realgrub** [Jeeaaasus/youtube-dl#39]
May be an unfortunate bit of renaming, but your docker build of yt-dlp does not seem to contain yt-dlp's SponSkrub integration to remove garbage from videos.

Container log shows "youtube-dl: error: no such option: --sponskrub-cut"

See https://github.com/yt-dlp/yt-dlp

**Comment by Jeeaaasus** [comment]
Hi there! :)
That's right. This [github](https://github.com/Jeeaaasus/youtube-dl/) and it's [images](https://hub.docker.com/r/jeeaaasustest/youtube-dl/) uses [youtube-dl](https://github.com/ytdl-org/youtube-dl) and not yt-dlp.

You must be confusing this project with another one.
