### ISSUE TITLE
Auto Download Playlists?

### ISSUE THREAD

**Issue by Airyzz** [Jeeaaasus/youtube-dl#43]
Hi, I was wondering if it could be possible to auto download videos based on a playlist?

I think it would be very useful to be able to auto download from things like 'Liked Videos', 'Watch Later' etc.

Thanks

**Comment by Jeeaaasus** [comment]
Hello @Airyzz! :)

This is totally possible already.

Any ordinary public playlist you simply add to the `channels.txt` file. Despite the name, this file may contain any kind of URL youtube-dl supports. ([Filesystem Options: --batch-file](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#filesystem-options))

In regards to private videos/playlists you have to authenticate with login ([Authentication Options](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#authentication-options)) or passing your cookies ([How do I pass cookies to youtube-dl?](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-pass-cookies-to-youtube-dl))

I would recommend passing your cookies, a quick guide:
Placing the `cookies.txt` file in the same folder as your `args.conf` and `channels.txt` files.
In `args.conf` you add a new line with `--cookies /config/cookies.txt`
In `channels.txt` you add your private URL. Watch Later is: `https://www.youtube.com/playlist?list=WL`, Liked Videos is: `https://www.youtube.com/playlist?list=LL`
Done.

I'm closing the issue but feel free to continue the conversation if you need more help! :)

**Comment by Airyzz** [comment]
That's perfect! thank you!
