### ISSUE TITLE
Changing to yt-dlp.

### ISSUE THREAD

**Issue by Jeeaaasus** [Jeeaaasus/youtube-dl#49]
A place for questions, feedback, discussion and issues in regards to the yt-dlp change.

**Comment by Jeeaaasus** [comment]
If you are using `%(playlist_index)` in your output format together with `--playlist-reverse`, the recommendation is to move to `%(playlist_autonumber)` and use `--compat-options playlist-index` instead.  More details [here](https://github.com/yt-dlp/yt-dlp/pull/302).

**Comment by Delver26** [comment]
I've been using the beta tag for the last few days now and it's working perfectly.
I've also been using some yt-dlp specific  arguments (--parse-metadata) and it's all working without issue.
Thanks!

**Comment by Jeeaaasus** [comment]
Hey @Delver26 I really appreciate you taking the time to let me know!
heads up, I pushed a new one recently. probably the last one before it goes to `latest`

**Comment by dingho** [comment]
@Jeeaaasus 
I'm also moving over from youtube-dl, and having some trouble getting my output format the same as I had it before.

My previous arguments from youtube-dl:
--playlist-reverse
-o "C:\Users\dingho\youtube-dl\download\%(uploader)s - S01E%(playlist_index)s - %(title)s.%(ext)s"

From yt-dlp:
--compat-options playlist-index
--playlist-reverse
-o "C:\Users\dingho\yt-dlp\download\%(uploader)s - S01E%(playlist_autonumber)s - %(title)s.%(ext)s"

It seems playlist_autonumber does not share a feature of playlist_index, namely, padding with leading zeros according to the total length of the playlist.  Is this intended?  It is making sorting somewhat difficult.

**Comment by Jeeaaasus** [comment]
Hi @dingho! :)
I'm not sure at all, but have you tried also using the `--compat-options playlist-index` arg mentioned in the thread above?
Otherwise you could try using `--compat-options youtube-dl`
> `--compat-options OPTS`
> Options that can help keep compatibility with youtube-dl or youtube-dlc configurations by reverting some of the
changes made in yt-dlp.
> See "Differences in default behavior" for details

**Comment by wsc96** [comment]
Seems that the pgrep command is no longer present in the docker image (neither is ps). Any suggestions for a suitable health check script to use within docker-compose.yml?

**Comment by Jeeaaasus** [comment]
Hi there @wsc96! Thanks :)

I personally haven't felt the need to have health checking because of how simple the container is, it's basically just a script running, ending and then starting again. I wouldn't know what to check for a health indicator. What are you checking?

Health checking a process seems kinda pointless to me, S6 is just restarting them when they die. Like the main bash script runs yt-dlp and then waits the interval time and then dies and the S6 overlay starts it again.
Checking if the webserver is alive is an option, but not everyone is going to want to have the webui running and currently it is not on by default.
The only useful health check I can think of is checking if it has internet access and that the webserver is alive, if enabled. It would be great if there's a way to have yt-dlp test if the config is valid, but I don't think that's a thing and even then, doesn't really seem worth it.

Maybe I should add health check for internet access? or maybe someone have a smart idea for a useful health check? I'm open for it. :)

**Comment by wsc96** [comment]
You're welcome.

So I've been simply doing a 'pgrep -fl youtube-dl.sh' as part of the health check. Very basic really and so probably doesn't provide a lot of value. I have some monitoring and alerting around containers that uses the container status health. I haven't been using the webserver.

I too would be interested if anyone else has something that adds a little more insight into the health.

Thanks again!
