### ISSUE TITLE
WebUI: (option for) automatic file renaming to prevent overwriting existing file

### ISSUE THREAD

**Issue by JulesCornelissen** [Jeeaaasus/youtube-dl#61]
First of all thank you for this project :)

Sometimes videos have identical names, especially on non-YouTube sites (such as past broadcasts on Twitch). Current behaviour is that whatever file was added last is the one that remains (i.e. the previous files get overwritten). An option to have it automatically rename would resolve this issue. Alternatively, an option to include the video ID in the filename would also solve this issue and would be my preferred solution.

**Comment by Jeeaaasus** [comment]
Hello @JulesCornelissen! :)

I understand your issue and different options/toggles within the webui downloader are **definitely needed yes** but this particular problem I realistically don't see how it could be fixed.

Instead I'm going to recommend to you, that you change your `--output` argument to include video ID, inside of your `args.conf` file.
When changed to something like: `--output '/downloads/%(uploader)s/%(title)s - %(id)s.%(ext)s'` (documentation [here](https://github.com/yt-dlp/yt-dlp#output-template))
Now every file name will include the ID, yes might not be a perfect solution, but I think it's the best one.

Let me know if you run into problems. :)
