### ISSUE TITLE
Custom options for each channel/playlist?

### ISSUE THREAD

**Issue by benfishbus** [Jeeaaasus/youtube-dl#66]
It would be extremely useful to be able to specify different ytdl options for each playlist/channel - use a special filename format, download as audio only, etc. One can always spin up additional ytdl containers for such playlists/channels, but a more elegant solution would be welcome.

**Comment by Jeeaaasus** [comment]
yep, this feature was JUST added in the last image update, but I have not written any documentation as of yet. You should be able to figure it out from my [comments on this issue thread, mainly this comment](https://github.com/Jeeaaasus/youtube-dl/issues/60#issuecomment-986085147). It's mostly explained there :)

This only works on images: `unstable`, `v2021.12.25` and `latest`

Feel free to ask if anything is unclear. :)

**Comment by benfishbus** [comment]
Oh, awesome! I'll try it out
