### ISSUE TITLE
[Feature request] add auto delete/trim logs after x amount of time

### ISSUE THREAD

**Issue by basings** [Jeeaaasus/youtube-dl#68]

**Comment by Jeeaaasus** [comment]
Hi there! :)

As of now there are no log files being created inside the container.
The logs you see when running `docker logs youtube-dl` is captured by the docker service and not something the container controls.

You can [change how docker handles logging](https://docs.docker.com/config/containers/logging/configure/) for a container.
You might be looking for something like this: `--log-opt max-buffer-size=4m`
