### ISSUE TITLE
syntax error near unexpected token `fi'

### ISSUE THREAD

**Issue by CasaPas** [Jeeaaasus/youtube-dl#72]
After the latest update I receive the above error and nothing downloads.

Any ideas?

**Comment by Jeeaaasus** [comment]
There was an issue but and I fixed it and then rebuilt the image yesterday.

Make sure you have the newest image, example updating using watchtower
```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --cleanup --run-once <CONTAINER_NAME>
```
It should return something similar to
`.. "Session done" Failed=0 Scanned=1 Updated=1 ..`

Please let me know how that goes :)
