### ISSUE TITLE
Rename the File from Greek to Greeklish

### ISSUE THREAD

**Issue by sakis-tech** [Jeeaaasus/youtube-dl#80]
Is there a way to automatically rename the filename from Greek to Greeklish?
as example: 
`γιασου` to `giasou`

edit:// i found this [site](https://spapas.github.io/2018/03/06/easy-youtube-mp3-downloading/) (scroll down until "**Fixing your unicode names**")

I can't get any further here, to be honest I'm still a noob, can someone help me?

p.s. i use Unraid.

**Comment by Jeeaaasus** [comment]
I don't think there is a built-in way no.

I'm sure you could figure out a way. Probably need to install some python dependencies and then automate the script using the --exec yt-dlp option.
