### ISSUE TITLE
Correct way to specify "best" format

### ISSUE THREAD

**Issue by Xalaxis** [Jeeaaasus/youtube-dl#81]
Hi there,

I was having a look at the use of the "youtubedl_quality" paramater and wondering the best way to specify "highest resolution available", essentially the default mode of yt-dlp? From what I understand from the usage in the code, this is actually the minimum resolution?

**Comment by Jeeaaasus** [comment]
Hi Xalaxis :)

No the youtubedl_quality number gets used as the highest possible vertical resolution that is allowed to be downloaded.

You can see the 'format' that is used here: https://github.com/Jeeaaasus/youtube-dl/blob/master/root/config.default/format

And you see the height<=youtubedl_quality, height equals or less than the variable.

If you wish to download the highest available you could define your own format in your args.conf. 
Or
Just make youtubedl_quality an unreasonably large number like 9000 or something.

**Comment by Xalaxis** [comment]
Perfect, thanks for the info!

Thanks also for developing this - I had my own version of this concept [started a while ago](https://github.com/Xalaxis/YouTube-Auto-Archive), but it needed several fixes, ideally a change to yt-dlp from og youtube-dl etc. This project seems like exactly what I'd planned on making!

Wishing you a Happy New Year 🎉 

Matthew

**Comment by Jeeaaasus** [comment]
Hey thank you and feel fully welcome to suggest features you want or help contribute directly! I am pretty happy with the current state of this project but it took quite a while.

Happy new year!
