### ISSUE TITLE
can the script download youtube music related artists?

### ISSUE THREAD

**Issue by cruix89** [Jeeaaasus/youtube-dl#85]
greetings,

its possible the script download music of youtube music, seeking for the related artists and downloading all that related?
like a automatic library music downloader?

the page of the artist its a youtube channel link and alone works, but exist a way to download related artists too?
its a good enchancement

thanks

**Comment by Jeeaaasus** [comment]
I have no clue, never used youtube music. If it's possible with yt-dlp it would be possible using my image.
