### ISSUE TITLE
[Request] Separate archive.txt entries per channel

### ISSUE THREAD

**Issue by Lreaper** [Jeeaaasus/youtube-dl#91]
Hi, I'm currently moving my setup from local sh scripts to youtube-dl docker container, In my previous setup I was using an archive.txt file per channel, would it be possible to add a section per channel inside the common archive.txt file?
Something like :

####channel Id: j32h4gj2h5j2j54
(video id)
(video id)
####channel id: 384567345h43
(videoid)

**Comment by Jeeaaasus** [comment]
No not really as the feature is currently. The archive.txt is simply the file that is used for the "--download-archive" file parameter from yt-dlp. Noting more, nothing less. What it does is record the IDs of all videos downloaded and uses it to skip downloads of videos already recorded. It will add any and all video IDs (along with the source identifier) to the end with no sorting what so ever, no matter the channel or even the source website.
```
--download-archive FILE         Download only videos not listed in the
                                archive file. Record the IDs of all
                                downloaded videos in it
```

However, in my https://github.com/Jeeaaasus/youtube-dl/tree/master#configure-youtube-dl section I mention how you can specify additional arguments to use with specific URLs within `channels.txt`, in this file you could specify a different `--download-archive <FILE>` for each channel or whatever to separate the archives. I don't really see the point but that's your choice. My implementation of `--download-archive` is nothing different from upstream yt-dlp.
