### ISSUE TITLE
Multiple configs?

### ISSUE THREAD

**Issue by ScribbleGhost** [Jeeaaasus/youtube-dl#95]
Hi. I am using this in Unraid as a container. Is there any way to have multiple config files? For example one for downloading audio files for music channels and another for videos?

**Comment by Jeeaaasus** [comment]
Sadly no, not explicitly. You can try some funky stuff with using the [additional args](https://github.com/Jeeaaasus/youtube-dl/tree/master?tab=readme-ov-file#configure-youtube-dl) feature in channels.txt but `/config/args.conf` will always be loaded first.

Probably a lot easier to just run two whole different containers.
