### ISSUE TITLE
mp3 download

### ISSUE THREAD

**Issue by klopp1991** [Jeeaaasus/youtube-dl#97]
All my channels with mp3 download. would be downloaded.

`https://www.youtube.com/@foo | --format mp3 --output '/downloads/podcast/foo/%(upload_date)s_%(fulltitle)s_%(channel)s_%(id)s.%(ext)s'`

**Comment by Jeeaaasus** [comment]
Found some guidance here: https://write.corbpie.com/downloading-youtube-videos-as-audio-with-yt-dlp/

I believe you are looking to use these options:
```
https://www.youtube.com/@foo | --extract-audio --audio-format mp3 --output '/downloads/podcast/foo/%(upload_date)s_%(fulltitle)s_%(channel)s_%(id)s.%(ext)s'
```
ref: https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#post-processing-options
