### ISSUE TITLE
Issue when I change the output path

### ISSUE THREAD

**Issue by AshCooperUK** [Jeeaaasus/youtube-dl#98]
Hey! fab little bit of software, I use it a lot. However when I change the output path using the below line, it also changes the thumbnail file, and because of the output-na-placeholder being set to nothing "" the channel avatar is getting renamed to "BBC Archive -  - .jpg" this is better than BBC Archive - NA - NA.jpg but is there a way of changing the channel avatar image to either thumb.jpg or default.jpg? as I use emby and would love to have the channel avatar as the folder image. I have tried : "--write-thumbnail --convert-thumbnails jpg -o "thumbnail.%(ext)s" but this is the video thumbnail and not the channel avatar. 

Any help would be appreciated! - once again! amazing work!

--output '/downloads/YouTube/%(channel)s/%(channel|)s - %(fulltitle|)s - %(upload_date>%d-%m-%Y|)s.%(ext)s'

Full config:
`
## args
--output-na-placeholder ''
--output '/downloads/YouTube/%(channel)s/%(channel|)s - %(fulltitle|)s - %(upload_date>%d-%m-%Y|)s.%(ext)s'
--force-ipv4

##options
#--write-info-json
#--write-description
--write-thumbnail
#--write-all-thumb

## Geo Restriction
--geo-bypass

## Video Selection
--playlist-end '2'
--match-filter 'original_url!*=/shorts/ & is_live != true'

## Download Options
--abort-on-unavailable-fragment
--playlist-reverse

## Filesystem Options
--windows-filenames
--no-part
--no-cache-dir

## Verbosity / Simulation Options
--ignore-no-formats-error
#--no-progress

## Workarounds
--sleep-requests '1'

## Video Format Options
--merge-output-format 'mp4'

## Subtitle Options
--sub-langs 'all,-live_chat'

## Post-Processing Options
#--embed-subs
--embed-thumbnail
--embed-metadata
#--convert-subs 'srt'

## SponsorBlock Options
--sponsorblock-mark 'all'
`

**Comment by Jeeaaasus** [comment]
Hello there! Always lovely hearing that others are getting use out of my little project!

I believe what you are looking to do is to define an additional `--output` option, specifically for playlist thumbnails. _(each channel is treated as a playlist by ytdlp)_ That would be done something like this:

```
--output 'pl_thumbnail:/downloads/YouTube/%(channel)s/thumb.%(ext)s'
```

By the looks of it you have plenty of experience with formatting the output to your need and probably know it better than me, but that will create a "thumb.jpg" in each channel folder.

I found this information [here](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template), just above the list of "available fields".

> you can set different output templates for the various metadata files separately from the general output template by specifying the type of file followed by the template separated by a colon `:`. The different file types supported are `subtitle`, `thumbnail`, `description`, `annotation` (deprecated), `infojson`, `link`, `pl_thumbnai`l, `pl_description`, `pl_infojson`, `chapter`, `pl_video`.

You should remove the `--output-na-placeholder ''`.

The updated full config would be this:
```
## args
--output '/downloads/YouTube/%(channel)s/%(channel|)s - %(fulltitle|)s - %(upload_date>%d-%m-%Y|)s.%(ext)s'
--output 'pl_thumbnail:/downloads/YouTube/%(channel)s/thumb.%(ext)s'
--force-ipv4

##options
#--write-info-json
#--write-description
--write-thumbnail
#--write-all-thumb

## Geo Restriction
--geo-bypass

## Video Selection
--playlist-end '2'
--match-filter 'original_url!*=/shorts/ & is_live != true'

## Download Options
--abort-on-unavailable-fragment
--playlist-reverse

## Filesystem Options
--windows-filenames
--no-part
--no-cache-dir

## Verbosity / Simulation Options
--ignore-no-formats-error
#--no-progress

## Workarounds
--sleep-requests '1'

## Video Format Options
--merge-output-format 'mp4'

## Subtitle Options
--sub-langs 'all,-live_chat'

## Post-Processing Options
#--embed-subs
--embed-thumbnail
--embed-metadata
#--convert-subs 'srt'

## SponsorBlock Options
--sponsorblock-mark 'all'
```

**Comment by AshCooperUK** [comment]
Thanks so much for your help, I ended up writing a script that runs as post-execution.sh but I did test your method, and it works. The only diffrence for my script I changes my output in args.conf to "--output '/downloads/YouTube/%(uploader_id)s/%(channel|)s - %(fulltitle|)s - %(upload_date>%d-%m-%Y|)s.%(ext)s'" . 

If anyone else needs it for emby here you go:

`#!/bin/bash

# Set the path to the YouTube downloads directory
downloads_dir="/downloads/YouTube"

# Array to hold directories that failed to download images
failed_downloads=()

# Function to fetch the channel avatar URL using the channel name
fetch_channel_avatar() {
    local channel_name="$1"
    local channel_url="https://www.youtube.com/${channel_name}"

    # Use wget to get the page content and extract avatar URL
    avatar_url=$(wget -q -O - "$channel_url" | grep -oP '(?<=<link rel="image_src" href=").*?(?=")')

    # Return the avatar URL
    echo "$avatar_url"
}

# Scan the /downloads/YouTube directory for channel folders
for channel_folder in "$downloads_dir"/*; do
    # Skip if it's not a directory
    if [[ ! -d "$channel_folder" ]]; then
        continue
    fi

    # Extract the channel name from the folder name
    channel_name=$(basename "$channel_folder")

    echo "Processing channel: $channel_name"

    # Fetch avatar URL
    avatar_url=$(fetch_channel_avatar "$channel_name")

    # Check if we successfully fetched the avatar URL
    if [[ -z "$avatar_url" ]]; then
        echo "Failed to retrieve avatar for channel: $channel_name"
        failed_downloads+=("$channel_folder (Failed to retrieve avatar)")
        continue
    fi

    # Download the avatar and save it as thumb.jpg in the existing channel folder
    wget -q -O "${channel_folder}/thumb.jpg" "$avatar_url"
    echo "Downloaded avatar for $channel_name"

    # Copy the avatar image to additional filenames
    cp "${channel_folder}/thumb.jpg" "${channel_folder}/logo.jpg"
    cp "${channel_folder}/thumb.jpg" "${channel_folder}/background.jpg"
    cp "${channel_folder}/thumb.jpg" "${channel_folder}/art.jpg"
    cp "${channel_folder}/thumb.jpg" "${channel_folder}/backdrop.jpg"
    echo "Copied thumb.jpg to logo.jpg, background.jpg, art.jpg, and backdrop.jpg for $channel_name"
done

# List directories that failed to download images
if [[ ${#failed_downloads[@]} -gt 0 ]]; then
    echo -e "\nThe following directories could not download images:"
    for failed_dir in "${failed_downloads[@]}"; do
        echo "$failed_dir"
    done
else
    echo -e "\nAll directories successfully downloaded images!"
fi
`
